networks:
  default:
    name: docker-network
    external: true


services:
  postgres:
    image: postgres:15
    hostname: db
    restart: unless-stopped
    volumes:
      - './pgdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=America/Sao_Paulo
    container_name: db
  wikijs:
    image: ghcr.io/requarks/wiki:2
    ports:
      - 8443:3443
      - 8082:3000
    hostname: wiki
    restart: unless-stopped
    environment:
      - UPGRADE_COMPANION=1
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_PORT=5432
      - DB_HOST=db
      - DB_TYPE=postgres
      - TZ=America/Sao_Paulo
    volumes:
        - './wiki/data/sideload:/etc/wiki/data/sideload'
    container_name: wikijs
  wiki-update-companion:
    image: ghcr.io/requarks/wiki-update-companion:latest
    hostname: wiki-update-companion
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    container_name: wiki-update-companion



# Acesse a UI em http://localhost:8082