name: pytorch-rocm
services:
    pytorch:
        image: rocm/pytorch:latest
        stdin_open: true
        tty: true
        network_mode: host
        devices:
            - /dev/kfd
            - /dev/dri
        group_add:
            - video
        ipc: host
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp=unconfined
        shm_size: 16G
        volumes:
            - $HOME/Documentos/docker/pytorch-rocm/dockerx:/dockerx
        working_dir: /dockerx
